-- CreateEnum
CREATE TYPE "RestaurantType" AS ENUM ('COMIDA_RAPIDA', 'CEVICHERIA', 'COCKTELERIA', 'BAR', 'PARRILLADA', 'RESTAURANTE', 'CAFETERIA', 'PIZZERIA', 'MARISQUERIA', 'OTRO');

-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN     "type" "RestaurantType" NOT NULL DEFAULT 'OTRO';
